services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pyephyom@gmail.com
      PGADMIN_DEFAULT_PASSWORD: demopassword
      PGADMIN_CONFIG_SERVER_MODE: 'False' # disable login
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False' # disable master password
    ports:
      - "5431:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:demopassword@db:5432/myapp
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  pgdata:
  pgadmin-data:
